module.exports = (function() {
  'use strict';

  let comments = [
  'Another day another dollar.',
  'Wow your job must suck.',
  'If you love something, set it free.',
  'If you hate it, cage it and make it your slave.',
  'Two heads are better than one.',
  'Unless they\'re on the same body.',
  'I know you are but what am I?',
  'Stupid.',
  'An apple a day keeps the doctor away.',
  'A doctor a day keeps everyone away.\'Cause you\'re a CANABLE!',
  'A little goes a long way.',
  'Especially if it\'s disease.',
  'What\'s mine is yours and what\'s yours is mine.',
  'Luckily, you have better stuff then me.',
  'Friendship is the greatest treasure of all.',
  'Unless you have a magic pony.',
  'Actions speak louder than words.',
  'And that\'s why nobody reads anymore.',
  'What doesn\'t kill you, makes you stronger.',
  'If you try it again, I garentee you\'ll die.',
  'A promise is a promise.',
  'And a lie is a lie.',
  'Who let the cat out of the bag?',
  'Obviously the one who knew it needed air.',
  'Knowledge is power. Ignorance is bliss.',
  'Well, which is it?!',
  'Why is it that every time disaster strikes, I find myself without a proper blade?',
  'Some cereals give me gas..',
  'Dancing on the table may be my favorite past time',
  'I really like banannas',
  'I have super powers',
  'I like to be naked',
  'I AM MAN! (WOMAN)',
  'I am the king (queen) of cheese!',
  'My hair hurts',
  'It\'s those damn aliens',
  'It\'s official.I\'m in love with HOT DOGS!',
  'Polar bears sleep with penguins, everyone knows that',
  'Why would I study if I can pretend to study?',
  'Community College is easier than sleeping with a prostitute',
  'IT\'S A CHALLENGE!',
  'I fear chipmunks..period',
  'Fupas are almost as sexy as your mom',
  'How dare you tempt me with those bolgarious schemes',
  'I was born at a very young age.',
  'I lost my necklace and dignity in the river.',
  'Are you afraid of raccoons?',
  'Ask me about allergy relief',
  'I want to punch bees in the face',
  'Why are you calling me while im pretending to be busy!',
  'Yay! I\'m taking a poop!',
  'well hello there dingleberry',
  'Hey, what happens in vegas stays in vegas!',
  'Yes, I would love to sled down your stairs',
  'Let\'s run through the sprinklers!',
  'Hemroids are a pain in the butt..',
  'genital herpes can be a hassle',
  'RUMSPRINGA!',
  'I hate when I have gum stuck in my hair',
  'Stand away, you smell like boiled cabbage',
  'Adventure time!',
  'Quick find the source of the lights!',
  'How dare you question my authority?',
  'Chitty Chitty bang bang!',
  'I\'ll go to the movies with you if you wait outside.',
  'Stand back, your hair makes me nervous',
  'I have never had this much fun since my last flash dance festival',
  'Your dog needs to stop licking my feet',
  'My name is (your name), but you can call me tomorrow',
  'If you eat too much cheese it can clog up your butt, be careful',
  'If barbie is so popular, why do you have to buy her friends?',
  'Running in place gets you nowhere, fast!',
  'If you dance with me I promise to step on your feet.',
  'Do you know what our state bird is?',
  'Do you know what our state tree is?',
  'When is national pie day?',
  'Could you refrain from drinking pop, it gives me gas.',
  'I prefer coke over pepsi.',
  'I like cats..',
  'I don\'t like cats..',
  'I am afraid of snow',
  'Sloppy Joes don\'t have to be sloppy if made differently',
  'The only way I can explain it is as seeing your 3rd grade math teacher naked',
  'My brain is swollen',
  'No paperclip, I do not need your help',
  'Why am I so amazing?',
  'I am about to loose my shoestring',
  'Do you have an extra earring that I can use?',
  'Please don\'t lick my face in that mannor',
  'If you pinch his butt I will give you a quarter',
  'I have read a total of 4 and 1/2 books in my lifetime',
  'You do know there are no real vampires?',
  'When you lick my armpits it tickles.',
  'Why say "I\'m fuming" if your not on fire?',
  'Yes this is my street, I own it',
  'If your house was in the middle of the street that would be very dangerous',
  'If you are Irish, you are born a great drinker.',
  'Dogs smaller than a football are not real dogs at all.',
  'It\'s 5:15 at nigh..do you know where your kids are?',
  'I dare you to show your face!',
  'If you park in the handicap spot I promise to limp into the store..',
  'Your gerbil is giving me the stink eye.',
  'Does this mean I get to keep my dictionary?',
  'You know I don\'t know spanish.',
  'I could see he wanted to joust with the table legs',
  'I have sass coming out of my ass',
  'SAFETY DANCE!',
  'No one makes me bleed my own blood',
  'My tire totally flew off of my car this morning',
  ' Would you like to kiss my flamingo?',
  'The penguins are in the kitchen.',
  'I carry eyeliner and small puppies in my purse.',
  'You support me, like a bra.',
  '88.We can\'t eat the bald eagle, they are endangered.',
  'Save the Whales!',
  'I own the heart of the ocean.',
  'You make me feel like I need to poop.',
  'When I sit, you stand..ready go!',
  'This weekend is the best night ever!',
  'I am super cool.',
  'Oh silly boy, tricks are for kids.',
  'Mommy always told me I would be prom King (queen)',
  'Lies are like fake truths',
  'If you ask for my number I may give you the rejection hotline',
  'Ninjas are really good at basketball.',
  'Sometimes your carpet makes me really angry.'];

  return {
    comments
  };


})();
